name: Nick Williams
tagline: Full-stack developer with a passion for JavaScript.
location: Leicestershire, UK
url: http://localhost:4000
twitter: http://twitter.com/nickwuh
github: https://github.com/nilliams
markdown: redcarpet
pygments: false
