name: Nick Williams
tagline: Full-stack developer with a passion for JavaScript.
location: Leicestershire, UK
twitter: http://twitter.com/nickwuh
github: https://github.com/nilliams
highlighter: null
permalink: /:title/
sass:
  sass_dir: _sass
  style: compressed
